package com.learning.backendservice.entity;

import com.learning.common.infra.tenant.TenantAuditingListener;
import com.learning.common.tenant.TenantAware;
import com.learning.common.tenant.TenantContext;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity for a generic audit run.
 * Replaces Rule37CalculationRun; supports all GST compliance modules.
 *
 * <p>Primary key is a UUID v7 (time-sorted) generated by the service layer
 * via {@code Generators.timeBasedReorderedGenerator().generate()}.
 * Migrated legacy records retain UUID v4 generated by {@code gen_random_uuid()}.
 */
@Entity
@Table(name = "audit_runs")
@EntityListeners(TenantAuditingListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuditRun implements TenantAware {

    /**
     * UUID v7 — time-sorted, globally unique, un-guessable.
     * NOT generated by DB; assigned by Java before persist.
     */
    @Id
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "tenant_id", nullable = false, length = 64)
    @Builder.Default
    private String tenantId = TenantContext.DEFAULT_TENANT;

    /** Keycloak user ID (sub claim) of the user who triggered this run */
    @Column(name = "user_id", nullable = false)
    private String userId;

    /** Identifies the AuditRule implementation; e.g. "RULE_37_ITC_REVERSAL" */
    @Column(name = "rule_id", nullable = false, length = 100)
    private String ruleId;

    /** PENDING | RUNNING | SUCCESS | FAILED */
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private String status = "PENDING";

    /** S3 object key for raw uploaded document (WORM audit trail) */
    @Column(name = "s3_raw_key", length = 500)
    private String s3RawKey;

    /**
     * Rule-specific input params stored as JSONB.
     * e.g. {"asOnDate":"2024-03-31","filename":"ledger.xlsx","migratedFromV1":false}
     */
    @Column(name = "input_metadata", columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private Object inputMetadata;

    /**
     * Rule-specific output stored as JSONB.
     * For Rule 37: List&lt;LedgerResult&gt;.
     * Deserialised in the service layer based on ruleId.
     */
    @Column(name = "result_data", columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private Object resultData;

    /** Aggregate financial impact = ITC reversal + interest + penalties */
    @Column(name = "total_impact_amount", nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal totalImpactAmount = BigDecimal.ZERO;

    /** Credits consumed for this run (1 credit per distinct supplier/ledger for Rule 37) */
    @Column(name = "credits_consumed", nullable = false)
    @Builder.Default
    private Integer creditsConsumed = 0;

    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    /** Retention expiry; auto-cleaned by RetentionScheduler. Default: 7 days. */
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    @OneToMany(mappedBy = "auditRun", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<AuditRunFinding> findings = new ArrayList<>();
}
